name: mappy2
description: Mappy 2.0, 16 months later

publish_to: "none"
version: 0.0.2+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0

  # Networking
  http: ^0.13.4

  # JSON serialization/deserialization annotations
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0

  # Flutter Mapbox GL + location
  mapbox_gl: ^0.16.0
  location: ^4.4.0

  # Utilities
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

  # Linter
  flutter_lints: ^2.0.1

  # Build runner
  build_runner: ^2.1.11

  # JSON serialization/deserialization
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

flutter_icons:
  android: launcher_icon
  ios: false
  image_path: assets/app_icon.png

flutter:
  uses-material-design: true
  assets:
    - assets/app_icon.png
    - assets/location_pin.png
